services:
  asxpio:
    # Image will be dynamically updated during deployment
    # Format: registry.example.com/user/asxpio:sha_tag
    build: .
    image: asxpio:latest
    container_name: asxpio
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asxpio.rule=Host(`asxp.io`) || Host(`www.asxp.io`)"
      - "traefik.http.routers.asxpio.entrypoints=websecure"
      - "traefik.http.routers.asxpio.tls=true"
      - "traefik.http.routers.asxpio.tls.certresolver=letsencrypt"
      - "traefik.http.services.asxpio.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
